version: '3.8'

volumes:
  pg_data: {}

services:
  bot:
    image: "${BOT_IMAGE_NAME:-tg_bot-image}"
    container_name: "${BOT_CONTAINER_NAME:-tg_bot-container}"
    stop_signal: SIGINT
    build:
      context: .
    volumes:
    - .:/usr/src/app/inside_gpt_bot
    - "./certs:/usr/src/certs"
    command: python3 -m bot
    restart: always
    env_file:
      - ".env"
#    depends_on:
#      - bot_mongo
    ports:
      - "8443:8443"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

#  bot_mongo:
#    image: mongodb/mongodb-community-server:6.0-ubi8
